# Generated by Django 3.2.4 on 2021-07-01 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('profile', models.CharField(blank=True, max_length=255, verbose_name='profile')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 57, 39, 941768, tzinfo=utc), verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 57, 39, 941804, tzinfo=utc), verbose_name='updated date')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 57, 39, 941823, tzinfo=utc), verbose_name='lastlogin date')),
                ('join_at', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 57, 39, 941839, tzinfo=utc), verbose_name='join date')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
